const rolls = [
  "Web Development",
  "Mobile Development",
  "UI/UX",
  "Data Science",
  "Business",
  "Writer",
  "Designer",
  "Marketer",
  "Frotend-dev",
  "Backend-dev",
  "Blockchain-dev",
  "Auditor",
  "Content creator",
  "Community Manager",
  "Bussiness Developer",
  "Data Scientist",
  "Analytics",
  "Ops",
  "Finance",
  "Founder",
  "Product",
  "Governance",
  "Degen",
];

module.exports = { rolls };
